export const ARTICLE_READ_REPOSITORY = "ARTICLE_READ_REPOSITORY";
export const ARTICLE_WRITE_REPOSITORY = "ARTICLE_WRITE_REPOSITORY";

export const BLOCK_READ_REPOSITORY = "BLOCK_READ_REPOSITORY";
export const BLOCK_WRITE_REPOSITORY = "BLOCK_WRITE_REPOSITORY";

export const COMMENT_READ_REPOSITORY = "COMMENT_READ_REPOSITORY";
export const COMMENT_WRITE_REPOSITORY = "COMMENT_WRITE_REPOSITORY";
