export const ARTICLE_REPOSITORY = "ARTICLE_REPOSITORY";

export const ARTICLE_BLOCK_OUTBOX_REPOSITORY =
  "ARTICLE_BLOCK_OUTBOX_REPOSITORY";

export const BLOCK_REPOSITORY = "BLOCK_REPOSITORY";

export const COMMENT_REPOSITORY = "COMMENT_REPOSITORY";
