export const ARTICLE_REPOSITORY = "ARTICLE_REPOSITORY";

export const BLOCK_REPOSITORY = "BLOCK_REPOSITORY";

export const COMMENT_REPOSITORY = "COMMENT_REPOSITORY";

export const TAG_REPOSITORY = "TAG_REPOSITORY";
