export enum MessageType {
  ARTICLE_CREATED = "ARTICLE_CREATED",
  ARTICLE_UPDATED = "ARTICLE_UPDATED",
  ARTICLE_DELETED = "ARTICLE_DELETED",
  ARTICLE_FAVORITED = "ARTICLE_FAVORITED",
  ARTICLE_UNFAVORITED = "ARTICLE_UNFAVORITED",
  COMMENT_CREATED = "COMMENT_CREATED",
  COMMENT_DELETED = "COMMENT_DELETED",
}

export enum MessageCmd {
  ARTICLE_CREATED = "ARTICLE_CREATED",
  ARTICLE_UPDATED = "ARTICLE_UPDATED",
  ARTICLE_DELETED = "ARTICLE_DELETED",
  ARTICLE_FAVORITED = "ARTICLE_FAVORITED",
  ARTICLE_UNFAVORITED = "ARTICLE_UNFAVORITED",
  COMMENT_CREATED = "COMMENT_CREATED",
  COMMENT_DELETED = "COMMENT_DELETED",
}
