export const USER_REPOSITORY = "USER_REPOSITORY";

export const ARTICLE_REPOSITORY = "ARTICLE_REPOSITORY";

export const BLOCK_REPOSITORY = "BLOCK_REPOSITORY";

export const COMMENT_REPOSITORY = "COMMENT_REPOSITORY";

export const FOLLOW_REPOSITORY = "FOLLOW_REPOSITORY";

export const TAG_REPOSITORY = "TAG_REPOSITORY";

export const MEDIA_REPOSITORY = "MEDIA_REPOSITORY";
